// On a 4x4 grid with at most four CGRAs per task, each task has eight oriented
// rectangular shapes. Of the 64 ordered pairs, exactly two cannot coexist:
// (A=1x4, B=4x1) and (A=4x1, B=1x4). Their total area fits, so excluding them
// verifies exact fixed-orientation packing.

// RUN: mlir-amoeba-opt %s \
// RUN:   '--enumerate-analytical-task-candidates=output=%t.candidates.jsonl max-cgras-per-task=4 max-candidates=62' \
// RUN:   --architecture-spec=%S/../../../archspec/architecture_4x4.yaml \
// RUN:   -o %t.bound.mlir
// RUN: FileCheck %s --input-file=%t.candidates.jsonl --check-prefix=CANDIDATES
// RUN: FileCheck %s --input-file=%t.bound.mlir --check-prefix=BOUND

module {
  func.func @main(%a: memref<16xf32>, %b: memref<16xf32>) {
    %a_read, %a_write = taskflow.task @A
        will_reads(%a : memref<16xf32>)
        will_writes(%a : memref<16xf32>)
        [original_read_memrefs(%a : memref<16xf32>),
         original_write_memrefs(%a : memref<16xf32>)]
        : (memref<16xf32>, memref<16xf32>)
       -> (memref<16xf32>, memref<16xf32>) {
    ^bb0(%input: memref<16xf32>, %output: memref<16xf32>):
      %c0 = arith.constant 0 : index
      %c10 = arith.constant 10 : index
      %c1 = arith.constant 1 : index
      %i = taskflow.counter from %c0 to %c10 step %c1 : index
      taskflow.yield done_reads(%input : memref<16xf32>)
                     done_writes(%output : memref<16xf32>)
    }
    %b_read, %b_write = taskflow.task @B
        will_reads(%b : memref<16xf32>)
        will_writes(%b : memref<16xf32>)
        [original_read_memrefs(%b : memref<16xf32>),
         original_write_memrefs(%b : memref<16xf32>)]
        : (memref<16xf32>, memref<16xf32>)
       -> (memref<16xf32>, memref<16xf32>) {
    ^bb0(%input: memref<16xf32>, %output: memref<16xf32>):
      %c0 = arith.constant 0 : index
      %c10 = arith.constant 10 : index
      %c1 = arith.constant 1 : index
      %i = taskflow.counter from %c0 to %c10 step %c1 : index
      taskflow.yield done_reads(%input : memref<16xf32>)
                     done_writes(%output : memref<16xf32>)
    }
    return
  }
}

// CANDIDATES-LABEL: {"architecture":{"grid_cols":4,"grid_rows":4,"per_cgra_tile_cols":4,"per_cgra_tile_rows":4,"spec_sha256":"1b96d6d3741805b057add7db66296c9c73cc45ea4ef0263e0eea5adb4f4360d6"},"cost_queries":[{"mapper_tile_cols":4,"mapper_tile_rows":4,"task":"A"},{"mapper_tile_cols":8,"mapper_tile_rows":4,"task":"A"},{"mapper_tile_cols":4,"mapper_tile_rows":8,"task":"A"},{"mapper_tile_cols":12,"mapper_tile_rows":4,"task":"A"},{"mapper_tile_cols":4,"mapper_tile_rows":12,"task":"A"},{"mapper_tile_cols":16,"mapper_tile_rows":4,"task":"A"},{"mapper_tile_cols":8,"mapper_tile_rows":8,"task":"A"},{"mapper_tile_cols":4,"mapper_tile_rows":16,"task":"A"},{"mapper_tile_cols":4,"mapper_tile_rows":4,"task":"B"},{"mapper_tile_cols":8,"mapper_tile_rows":4,"task":"B"},{"mapper_tile_cols":4,"mapper_tile_rows":8,"task":"B"},{"mapper_tile_cols":12,"mapper_tile_rows":4,"task":"B"},{"mapper_tile_cols":4,"mapper_tile_rows":12,"task":"B"},{"mapper_tile_cols":16,"mapper_tile_rows":4,"task":"B"},{"mapper_tile_cols":8,"mapper_tile_rows":8,"task":"B"},{"mapper_tile_cols":4,"mapper_tile_rows":16,"task":"B"}],"fixed_axes":{"communication":"not-scored","fission":"factor-1","fusion":"identity","placement":"exact-fit-required-coordinates-downstream-heuristic","temporal_order":"downstream-heuristic","tiling":"factor-1"},"function":"main","max_cgras_per_task":4,"record_type":"header","schema":"amoeba-analytical-task-candidates","search_scope":"static-shape-concurrent-fit","shape_policy":"static-oriented-rectangles","spatial_capacity_policy":"all-tasks-simultaneous-exact-pack","tasks":[{"body_sha256":"f4e821880514d53c4c0fdd5866807dca5eeb44b23220207881ad7846ef3308fe","task":"A","trip_count":10},{"body_sha256":"f4e821880514d53c4c0fdd5866807dca5eeb44b23220207881ad7846ef3308fe","task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-0","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-1","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-2","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-3","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-4","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-5","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-6","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-7","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-8","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-9","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-10","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-11","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-12","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-13","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-14","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-15","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-16","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-17","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-18","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-19","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-20","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-21","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-22","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-23","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-24","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-25","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-26","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-27","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-28","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-29","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-30","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-31","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-32","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-33","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-34","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-35","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-36","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-37","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-38","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-39","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-40","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-41","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-42","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-43","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-44","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-45","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-46","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-47","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-48","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-49","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-50","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-51","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-52","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"1x4","cols":4,"kind":"rect","mapper_tile_cols":16,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-53","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-54","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-55","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":1,"cgra_shape":"1x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-56","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"1x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-57","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":2,"cgra_shape":"2x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-58","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"1x3","cols":3,"kind":"rect","mapper_tile_cols":12,"mapper_tile_rows":4,"rows":1},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-59","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":3,"cgra_shape":"3x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":12,"rows":3},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-60","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"2x2","cols":2,"kind":"rect","mapper_tile_cols":8,"mapper_tile_rows":8,"rows":2},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_id":"candidate-61","record_type":"candidate","schema":"amoeba-analytical-task-candidates","task_shapes":[{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"A","trip_count":10},{"shape":{"cgra_count":4,"cgra_shape":"4x1","cols":1,"kind":"rect","mapper_tile_cols":4,"mapper_tile_rows":16,"rows":4},"task":"B","trip_count":10}]}
// CANDIDATES-NEXT: {"candidate_count":62,"record_type":"footer","schema":"amoeba-analytical-task-candidates"}

// BOUND-LABEL: module {
// BOUND-NEXT:   func.func @main(%arg0: memref<16xf32>, %arg1: memref<16xf32>) {
// BOUND-NEXT:     %done_reads, %done_writes = taskflow.task @A will_reads(%arg0 : memref<16xf32>) will_writes(%arg0 : memref<16xf32>) [original_read_memrefs(%arg0 : memref<16xf32>), original_write_memrefs(%arg0 : memref<16xf32>)] {amoeba.source_task_body_sha256 = "f4e821880514d53c4c0fdd5866807dca5eeb44b23220207881ad7846ef3308fe"} : (memref<16xf32>, memref<16xf32>) -> (memref<16xf32>, memref<16xf32>) {
// BOUND-NEXT:     ^bb0(%arg2: memref<16xf32>, %arg3: memref<16xf32>):
// BOUND-NEXT:       %c0 = arith.constant 0 : index
// BOUND-NEXT:       %c10 = arith.constant 10 : index
// BOUND-NEXT:       %c1 = arith.constant 1 : index
// BOUND-NEXT:       %0 = taskflow.counter from %c0 to %c10 step %c1 : index
// BOUND-NEXT:       taskflow.yield done_reads(%arg2 : memref<16xf32>) done_writes(%arg3 : memref<16xf32>)
// BOUND-NEXT:     }
// BOUND-NEXT:     %done_reads_0, %done_writes_1 = taskflow.task @B will_reads(%arg1 : memref<16xf32>) will_writes(%arg1 : memref<16xf32>) [original_read_memrefs(%arg1 : memref<16xf32>), original_write_memrefs(%arg1 : memref<16xf32>)] {amoeba.source_task_body_sha256 = "f4e821880514d53c4c0fdd5866807dca5eeb44b23220207881ad7846ef3308fe"} : (memref<16xf32>, memref<16xf32>) -> (memref<16xf32>, memref<16xf32>) {
// BOUND-NEXT:     ^bb0(%arg2: memref<16xf32>, %arg3: memref<16xf32>):
// BOUND-NEXT:       %c0 = arith.constant 0 : index
// BOUND-NEXT:       %c10 = arith.constant 10 : index
// BOUND-NEXT:       %c1 = arith.constant 1 : index
// BOUND-NEXT:       %0 = taskflow.counter from %c0 to %c10 step %c1 : index
// BOUND-NEXT:       taskflow.yield done_reads(%arg2 : memref<16xf32>) done_writes(%arg3 : memref<16xf32>)
// BOUND-NEXT:     }
// BOUND-NEXT:     return
// BOUND-NEXT:   }
// BOUND-NEXT: }
